[project]
name = "langgraph-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain>=0.3.17",
    "langchain-groq>=0.2.4",
    "langgraph>=0.2.69",
    "pydantic>=2.10.6",
]
